import PyMKF

material_data = PyMKF.find_core_material_by_name("3C97")
print(material_data)


magnetic = {'coil': {'bobbin': {'distributorsInfo': None,
                         'functionalDescription': None,
                         'manufacturerInfo': None,
                         'name': None,
                         'processedDescription': {'columnDepth': 0.0042,
                                                  'columnShape': 'rectangular',
                                                  'columnThickness': 0.00065,
                                                  'columnWidth': 0.0007,
                                                  'coordinates': [0, 0, 0],
                                                  'pins': None,
                                                  'wallThickness': 0.0004999999999999996,
                                                  'windingWindows': [{'angle': 360,
                                                                      'area': 6.514406526483796e-06,
                                                                      'coordinates': [0.00144,
                                                                                      0,
                                                                                      0],
                                                                      'height': None,
                                                                      'radialHeight': 0.00144,
                                                                      'sectionsOrientation': 'contiguous',
                                                                      'shape': 'round',
                                                                      'width': None}]}},
              'functionalDescription': [{'connections': None,
                                         'isolationSide': 'primary',
                                         'name': 'primary',
                                         'numberParallels': 1,
                                         'numberTurns': 4,
                                         'wire': {'coating': {'breakdownVoltage': 7600,
                                                              'grade': 3,
                                                              'material': None,
                                                              'numberLayers': None,
                                                              'temperatureRating': None,
                                                              'thickness': None,
                                                              'thicknessLayers': None,
                                                              'type': 'enamelled'},
                                                  'conductingArea': {'excludeMaximum': None,
                                                                     'excludeMinimum': None,
                                                                     'maximum': None,
                                                                     'minimum': None,
                                                                     'nominal': 4.116868676970209e-07},
                                                  'conductingDiameter': {'excludeMaximum': None,
                                                                         'excludeMinimum': None,
                                                                         'maximum': None,
                                                                         'minimum': None,
                                                                         'nominal': 0.000724},
                                                  'conductingHeight': None,
                                                  'conductingWidth': None,
                                                  'edgeRadius': None,
                                                  'manufacturerInfo': {'cost': None,
                                                                       'datasheetUrl': None,
                                                                       'family': None,
                                                                       'name': 'Nearson',
                                                                       'orderCode': None,
                                                                       'reference': None,
                                                                       'status': None},
                                                  'material': 'copper',
                                                  'name': '21.0 - Triple Build',
                                                  'numberConductors': 1,
                                                  'outerDiameter': {'excludeMaximum': None,
                                                                    'excludeMinimum': None,
                                                                    'maximum': None,
                                                                    'minimum': None,
                                                                    'nominal': 0.000815},
                                                  'outerHeight': None,
                                                  'outerWidth': None,
                                                  'standard': 'NEMA MW 1000 C',
                                                  'standardName': '21.0',
                                                  'strand': None,
                                                  'type': 'round'}}],
              'layersDescription': [{'additionalCoordinates': None,
                                     'coordinateSystem': 'polar',
                                     'coordinates': [0.0004075000000000001,
                                                     272.98235669020863],
                                     'dimensions': [0.000815, 185.96471338041727],
                                     'fillingFactor': 0.830152183167326,
                                     'insulationMaterial': None,
                                     'name': 'primary section 0 layer 0',
                                     'orientation': 'overlapping',
                                     'partialWindings': [{'connections': None,
                                                          'parallelsProportion': [1],
                                                          'winding': 'primary'}],
                                     'section': 'primary section 0',
                                     'turnsAlignment': 'centered',
                                     'type': 'conduction',
                                     'windingStyle': 'windByConsecutiveTurns'}],
              'sectionsDescription': [{'coordinateSystem': 'polar',
                                       'coordinates': [0.0004075000000000001,
                                                       272.98235669020863],
                                       'dimensions': [0.000815, 185.96471338041727],
                                       'fillingFactor': 0.40784989226548674,
                                       'layersAlignment': None,
                                       'layersOrientation': 'overlapping',
                                       'margin': [0, 0],
                                       'name': 'primary section 0',
                                       'partialWindings': [{'connections': None,
                                                            'parallelsProportion': [1],
                                                            'winding': 'primary'}],
                                       'type': 'conduction',
                                       'windingStyle': 'windByConsecutiveTurns'}],
              'turnsDescription': [{'additionalCoordinates': [[-0.0029838731335854515,
                                                               -0.0012817009685051118]],
                                    'angle': None,
                                    'coordinateSystem': 'cartesian',
                                    'coordinates': [-0.0009486832980529571,
                                                    -0.0004074999999943119],
                                    'dimensions': [0.000815, 0.000815],
                                    'layer': 'primary section 0 layer 0',
                                    'length': 0.02216039801267568,
                                    'name': 'primary parallel 0 turn 0',
                                    'orientation': 'clockwise',
                                    'parallel': 0,
                                    'rotation': 110.263232482,
                                    'section': 'primary section 0',
                                    'winding': 'primary'},
                                   {'additionalCoordinates': [[-0.0011247187670692276,
                                                               -0.0030465166904191216]],
                                    'angle': None,
                                    'coordinateSystem': 'cartesian',
                                    'coordinates': [-0.00035758956951469664,
                                                    -0.0009685999947213989],
                                    'dimensions': [0.000815, 0.000815],
                                    'layer': 'primary section 0 layer 0',
                                    'length': 0.02216039801267568,
                                    'name': 'primary parallel 0 turn 1',
                                    'orientation': 'clockwise',
                                    'parallel': 0,
                                    'rotation': 156.75441082710432,
                                    'section': 'primary section 0',
                                    'winding': 'primary'},
                                   {'additionalCoordinates': [[0.0014352113071608814,
                                                               -0.0029131468816037333]],
                                    'angle': None,
                                    'coordinateSystem': 'cartesian',
                                    'coordinates': [0.00045630659727285906,
                                                    -0.0009261968145514563],
                                    'dimensions': [0.000815, 0.000815],
                                    'layer': 'primary section 0 layer 0',
                                    'length': 0.02216039801267568,
                                    'name': 'primary parallel 0 turn 2',
                                    'orientation': 'clockwise',
                                    'parallel': 0,
                                    'rotation': 203.24558917220864,
                                    'section': 'primary section 0',
                                    'winding': 'primary'},
                                   {'additionalCoordinates': [[0.0031009078636953344,
                                                               -0.0009646899350944004]],
                                    'angle': None,
                                    'coordinateSystem': 'cartesian',
                                    'coordinates': [0.0009858929543542518,
                                                    -0.0003067105028437162],
                                    'dimensions': [0.000815, 0.000815],
                                    'layer': 'primary section 0 layer 0',
                                    'length': 0.02216039801267568,
                                    'name': 'primary parallel 0 turn 3',
                                    'orientation': 'clockwise',
                                    'parallel': 0,
                                    'rotation': 249.73676751731296,
                                    'section': 'primary section 0',
                                    'winding': 'primary'}]},
     'core': {'distributorsInfo': [{'cost': 0.27,
                                    'country': 'USA',
                                    'distributedArea': 'International',
                                    'email': None,
                                    'link': 'https://www.digikey.com/en/products/detail/fair-rite-products-corp/5980000101/17370492',
                                    'name': 'Digi-Key',
                                    'phone': None,
                                    'quantity': 1858,
                                    'reference': '1934-5980000101-ND',
                                    'updatedAt': '16/04/2024'}],
              'functionalDescription': {'coating': None,
                                        'gapping': [],
                                        'material': {'bhCycle': None,
                                                     'coerciveForce': [{'magneticField': 37,
                                                                        'magneticFluxDensity': 0,
                                                                        'temperature': 100},
                                                                       {'magneticField': 32,
                                                                        'magneticFluxDensity': 0,
                                                                        'temperature': 25}],
                                                     'curieTemperature': 300,
                                                     'density': 4800,
                                                     'family': 'MnZn',
                                                     'heatCapacity': None,
                                                     'heatConductivity': None,
                                                     'manufacturerInfo': {'cost': None,
                                                                          'datasheetUrl': None,
                                                                          'family': None,
                                                                          'name': 'Fair-Rite',
                                                                          'orderCode': None,
                                                                          'reference': None,
                                                                          'status': None},
                                                     'materialComposition': 'ferrite',
                                                     'name': '80',
                                                     'permeability': {'amplitude': None,
                                                                      'initial': [{'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': -40,
                                                                                   'tolerance': None,
                                                                                   'value': 609.09},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': -10,
                                                                                   'tolerance': None,
                                                                                   'value': 611.2},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 0,
                                                                                   'tolerance': None,
                                                                                   'value': 618.1},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 10,
                                                                                   'tolerance': None,
                                                                                   'value': 618.25},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 20,
                                                                                   'tolerance': None,
                                                                                   'value': 611.93},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 25,
                                                                                   'tolerance': None,
                                                                                   'value': 605},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 30,
                                                                                   'tolerance': None,
                                                                                   'value': 596.23},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 35,
                                                                                   'tolerance': None,
                                                                                   'value': 585.6},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 40,
                                                                                   'tolerance': None,
                                                                                   'value': 575.52},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 45,
                                                                                   'tolerance': None,
                                                                                   'value': 564.08},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 50,
                                                                                   'tolerance': None,
                                                                                   'value': 553.64},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 55,
                                                                                   'tolerance': None,
                                                                                   'value': 542.32},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 60,
                                                                                   'tolerance': None,
                                                                                   'value': 531.75},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 70,
                                                                                   'tolerance': None,
                                                                                   'value': 514.56},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 80,
                                                                                   'tolerance': None,
                                                                                   'value': 502.39},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 90,
                                                                                   'tolerance': None,
                                                                                   'value': 489.43},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 100,
                                                                                   'tolerance': None,
                                                                                   'value': 481.72},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 110,
                                                                                   'tolerance': None,
                                                                                   'value': 474.8},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 120,
                                                                                   'tolerance': None,
                                                                                   'value': 470.51},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 130,
                                                                                   'tolerance': None,
                                                                                   'value': 469.04},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 135,
                                                                                   'tolerance': None,
                                                                                   'value': 468.7},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 140,
                                                                                   'tolerance': None,
                                                                                   'value': 468.21},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 145,
                                                                                   'tolerance': None,
                                                                                   'value': 467.99},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 150,
                                                                                   'tolerance': None,
                                                                                   'value': 470.32},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 155,
                                                                                   'tolerance': None,
                                                                                   'value': 472.26},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 160,
                                                                                   'tolerance': None,
                                                                                   'value': 474.66},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 170,
                                                                                   'tolerance': None,
                                                                                   'value': 482.37},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 180,
                                                                                   'tolerance': None,
                                                                                   'value': 489.69},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 195,
                                                                                   'tolerance': None,
                                                                                   'value': 508.43},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 200,
                                                                                   'tolerance': None,
                                                                                   'value': 512.22},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 225,
                                                                                   'tolerance': None,
                                                                                   'value': 541.99},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 250,
                                                                                   'tolerance': None,
                                                                                   'value': 578.19},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 275,
                                                                                   'tolerance': None,
                                                                                   'value': 638.53},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 300,
                                                                                   'tolerance': None,
                                                                                   'value': 788.58},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 305,
                                                                                   'tolerance': None,
                                                                                   'value': 860.72},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 315,
                                                                                   'tolerance': None,
                                                                                   'value': 84.48},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 325,
                                                                                   'tolerance': None,
                                                                                   'value': 7.39},
                                                                                  {'frequency': 10000,
                                                                                   'magneticFieldDcBias': None,
                                                                                   'magneticFluxDensityPeak': None,
                                                                                   'modifiers': None,
                                                                                   'temperature': 330,
                                                                                   'tolerance': None,
                                                                                   'value': 3.14}]},
                                                     'remanence': [{'magneticField': 0,
                                                                    'magneticFluxDensity': 0.048,
                                                                    'temperature': 100},
                                                                   {'magneticField': 0,
                                                                    'magneticFluxDensity': 0.044,
                                                                    'temperature': 25}],
                                                     'resistivity': [{'temperature': 25,
                                                                      'value': 2}],
                                                     'saturation': [{'magneticField': 393,
                                                                     'magneticFluxDensity': 0.4,
                                                                     'temperature': 100},
                                                                    {'magneticField': 392,
                                                                     'magneticFluxDensity': 0.473,
                                                                     'temperature': 25}],
                                                     'type': 'commercial',
                                                     'volumetricLosses': {'default': [{'a': None,
                                                                                       'b': None,
                                                                                       'c': None,
                                                                                       'coefficients': None,
                                                                                       'd': None,
                                                                                       'method': 'roshen',
                                                                                       'ranges': None,
                                                                                       'referenceVolumetricLosses': None},
                                                                                      {'a': None,
                                                                                       'b': None,
                                                                                       'c': None,
                                                                                       'coefficients': None,
                                                                                       'd': None,
                                                                                       'method': 'steinmetz',
                                                                                       'ranges': [{'alpha': 1.50260692,
                                                                                                   'beta': 3.267013187,
                                                                                                   'ct0': 0.9226637419,
                                                                                                   'ct1': 0.001434689081,
                                                                                                   'ct2': 8.94716207e-05,
                                                                                                   'k': 3.625236705,
                                                                                                   'maximumFrequency': 1500000,
                                                                                                   'minimumFrequency': 1000000},
                                                                                                  {'alpha': 1.287854767,
                                                                                                   'beta': 2.62022147,
                                                                                                   'ct0': 1.440454324,
                                                                                                   'ct1': 0.001456775336,
                                                                                                   'ct2': 0.0001287487906,
                                                                                                   'k': 6.826856556,
                                                                                                   'maximumFrequency': 2500000,
                                                                                                   'minimumFrequency': 1500000},
                                                                                                  {'alpha': 1.226673768,
                                                                                                   'beta': 2.234346501,
                                                                                                   'ct0': 1.266458376,
                                                                                                   'ct1': 0.001452870585,
                                                                                                   'ct2': 0.0001498738833,
                                                                                                   'k': 6.833268406,
                                                                                                   'maximumFrequency': 3500000,
                                                                                                   'minimumFrequency': 2500000},
                                                                                                  {'alpha': 1.244538958,
                                                                                                   'beta': 2.118645804,
                                                                                                   'ct0': 0.9984019564,
                                                                                                   'ct1': 0.001720359565,
                                                                                                   'ct2': 4.158073494e-05,
                                                                                                   'k': 6.836519781,
                                                                                                   'maximumFrequency': 4000000,
                                                                                                   'minimumFrequency': 3500000}],
                                                                                       'referenceVolumetricLosses': None}]}},
                                        'numberStacks': 3,
                                        'shape': {'aliases': [],
                                                  'dimensions': {'A': {'excludeMaximum': None,
                                                                       'excludeMinimum': None,
                                                                       'maximum': None,
                                                                       'minimum': None,
                                                                       'nominal': 0.00568},
                                                                 'B': {'excludeMaximum': None,
                                                                       'excludeMinimum': None,
                                                                       'maximum': None,
                                                                       'minimum': None,
                                                                       'nominal': 0.00288},
                                                                 'C': {'excludeMaximum': None,
                                                                       'excludeMinimum': None,
                                                                       'maximum': None,
                                                                       'minimum': None,
                                                                       'nominal': 0.0014}},
                                                  'family': 't',
                                                  'familySubtype': None,
                                                  'magneticCircuit': 'closed',
                                                  'name': 'T 5.7/2.88/1.4',
                                                  'type': 'standard'},
                                        'type': 'toroidal'},
              'geometricalDescription': None,
              'manufacturerInfo': {'cost': None,
                                   'datasheetUrl': 'https://fair-rite.com/product/toroids-5980000101/',
                                   'family': None,
                                   'name': 'Fair-Rite',
                                   'orderCode': None,
                                   'reference': '5980000101',
                                   'status': 'production'},
              'name': 'T 5.7/2.88/1.4 - 80 - Ungapped',
              'processedDescription': {'columns': [{'area': 1.2e-05,
                                                    'coordinates': [0, 0, 0],
                                                    'depth': 0.0084,
                                                    'height': 0.013446016557364314,
                                                    'minimumDepth': None,
                                                    'minimumWidth': None,
                                                    'shape': 'rectangular',
                                                    'type': 'central',
                                                    'width': 0.0014}],
                                       'depth': 0.0084,
                                       'effectiveParameters': {'effectiveArea': 1.1759999999999996e-05,
                                                               'effectiveLength': 0.01344601655736431,
                                                               'effectiveVolume': 1.5812515471460424e-07,
                                                               'minimumArea': 1.176e-05},
                                       'height': 0.00568,
                                       'width': 0.00568,
                                       'windingWindows': [{'angle': 360,
                                                           'area': 6.514406526483796e-06,
                                                           'coordinates': [0.0014,
                                                                           0],
                                                           'height': None,
                                                           'radialHeight': 0.00144,
                                                           'sectionsOrientation': None,
                                                           'shape': None,
                                                           'width': None}]}},
     'distributorsInfo': None,
     'manufacturerInfo': {'cost': None,
                          'datasheetUrl': None,
                          'family': None,
                          'name': '',
                          'recommendations': None,
                          'reference': 'T 5.7/2.88/1.4 - 80 - Ungapped 3 stacks, '
                                       'Turns: 4, Order: 0, Non-Interleaved, '
                                       'Margin Taped 00',
                          'status': None},
     'rotation': None}

result = PyMKF.plot_turns(magnetic, "test.svg")
print(result)
