# Project information
site_name: PyMKF
site_description: Python wrapper for MKF module of OpenMagnetics
site_author: tinix84
site_url: https://github.com/tinix84/PyMKF

# Repository
repo_name: yourusername/PyMKF
repo_url: https://github.com/tinix84/PyMKF
edit_uri: edit/main/docs/docs/

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Plugins
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: numpy
            show_source: true
  - git-revision-date-localized:
      type: date
  - mkdocs-jupyter:
      include_source: true

# Extra CSS
extra_css:
  - css/custom.css

# Navigation
nav:
  - Home: index.md
  - Installation: installation.md
  - API Reference: api.md
  - Examples: examples.md

# Additional settings
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tinix84/PyMKF
      name: tinix84
  version:
    provider: mike